import { useState, useEffect } from 'react'
import { Signal, TrendingUp, TrendingDown } from 'lucide-react'
import { api } from '../services/api'

const SignalsTab = () => {
  const [signals, setSignals] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchSignals()
    const interval = setInterval(fetchSignals, 5000)
    return () => clearInterval(interval)
  }, [])

  const fetchSignals = async () => {
    try {
      const response = await api.get('/market/signals?limit=50')
      setSignals(response.data.signals)
      setLoading(false)
    } catch (error) {
      console.error('Error fetching signals:', error)
      setLoading(false)
    }
  }

  if (loading) {
    return <div className="text-center py-8 text-muted">Loading signals…</div>
  }

  return (
    <div className="space-y-5">
      <div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
        <div>
          <h2 className="heading-lg text-xl">Active Trading Signals</h2>
          <p className="text-sm text-muted">Live intelligence generated by Cryptopulse AI</p>
        </div>
        <span className="text-sm text-muted uppercase tracking-[0.4em]">
          {signals.length} signals
        </span>
      </div>

      <div className="overflow-x-auto rounded-3xl border border-white/5">
        <table className="min-w-full divide-y divide-white/6 text-sm">
          <thead className="bg-ocean-900/60">
            <tr className="text-left text-xs font-semibold uppercase tracking-[0.4em] text-muted">
              <th className="px-6 py-4">Exchange</th>
              <th className="px-6 py-4">Pair</th>
              <th className="px-6 py-4">Type</th>
              <th className="px-6 py-4">Entry Price</th>
              <th className="px-6 py-4">Stop Loss</th>
              <th className="px-6 py-4">Take Profit</th>
              <th className="px-6 py-4">Confidence</th>
              <th className="px-6 py-4">Created</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/5 bg-ocean-900/30">
            {signals.map((signal) => (
              <tr
                key={signal.id}
                className="transition hover:bg-ocean-900/60 hover:backdrop-blur-md"
              >
                <td className="px-6 py-4 font-medium text-accent-100">{signal.exchange_name}</td>
                <td className="px-6 py-4 text-accent-100/90">{signal.trading_pair}</td>
                <td className="px-6 py-4">
                  {signal.signal_type === 'BUY' ? (
                    <span className="inline-flex items-center gap-1 rounded-full bg-success/10 px-3 py-1 text-xs font-medium text-success">
                      <TrendingUp className="h-3 w-3" />
                      BUY
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1 rounded-full bg-danger/10 px-3 py-1 text-xs font-medium text-danger">
                      <TrendingDown className="h-3 w-3" />
                      SELL
                    </span>
                  )}
                </td>
                <td className="px-6 py-4 text-accent-100/90">
                  ${parseFloat(signal.entry_price).toFixed(2)}
                </td>
                <td className="px-6 py-4 text-accent-100/90">
                  ${parseFloat(signal.stop_loss).toFixed(2)}
                </td>
                <td className="px-6 py-4 text-accent-100/90">
                  ${parseFloat(signal.take_profit).toFixed(2)}
                </td>
                <td className="px-6 py-4">
                  <div className="inline-flex items-center gap-2 rounded-full border border-accent-400/30 bg-accent-500/10 px-3 py-1 text-xs font-medium text-accent-200">
                    <Signal className="h-3 w-3" />
                    {signal.confidence_score}%
                  </div>
                </td>
                <td className="px-6 py-4 text-muted">
                  {new Date(signal.created_at).toLocaleString()}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default SignalsTab

